# Generated by Django 5.1.4 on 2025-02-19 13:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RW'),
        ),
        migrations.AlterField(
            model_name='level1profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RW'),
        ),
        migrations.AlterField(
            model_name='level2profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RW'),
        ),
        migrations.AlterField(
            model_name='level3profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RW'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RW'),
        ),
    ]
