# Generated by Django 5.1.4 on 2025-02-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_companyprofile_phone_alter_level1profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1 - Skilled but No Certification'), ('level2', 'Level 2 - Certified Professional'), ('level3', 'Level 3 - Expert/Business'), ('company', 'Company Hiring')], default='company', max_length=20),
        ),
        migrations.AddField(
            model_name='level1profile',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1 - Skilled but No Certification'), ('level2', 'Level 2 - Certified Professional'), ('level3', 'Level 3 - Expert/Business'), ('company', 'Company Hiring')], default='level1', max_length=20),
        ),
        migrations.AddField(
            model_name='level2profile',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1 - Skilled but No Certification'), ('level2', 'Level 2 - Certified Professional'), ('level3', 'Level 3 - Expert/Business'), ('company', 'Company Hiring')], default='level2', max_length=20),
        ),
        migrations.AddField(
            model_name='level3profile',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1 - Skilled but No Certification'), ('level2', 'Level 2 - Certified Professional'), ('level3', 'Level 3 - Expert/Business'), ('company', 'Company Hiring')], default='level3', max_length=20),
        ),
    ]
