# Generated by Django 5.1.4 on 2025-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_companyprofile_level_level1profile_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1 - Skilled but No Certification'), ('level2', 'Level 2 - Certified Professional'), ('level3', 'Level 3 - Expert/Business'), ('company', 'Company Hiring')], default='company', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='level1profile',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1 - Skilled but No Certification'), ('level2', 'Level 2 - Certified Professional'), ('level3', 'Level 3 - Expert/Business'), ('company', 'Company Hiring')], default='level1', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='level2profile',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1 - Skilled but No Certification'), ('level2', 'Level 2 - Certified Professional'), ('level3', 'Level 3 - Expert/Business'), ('company', 'Company Hiring')], default='level2', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='level3profile',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1 - Skilled but No Certification'), ('level2', 'Level 2 - Certified Professional'), ('level3', 'Level 3 - Expert/Business'), ('company', 'Company Hiring')], default='level3', editable=False, max_length=20),
        ),
    ]
