# Generated by Django 5.2 on 2025-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_level2profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='level1profile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('booked_today', 'Booked Today'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='level1profile',
            name='next_available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
