# Generated by Django 5.2 on 2025-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_level1profile_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level2profile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('booked_today', 'Booked Today'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='level2profile',
            name='next_available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level3profile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('booked_today', 'Booked Today'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='level3profile',
            name='next_available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
