# Generated by Django 5.2 on 2025-05-02 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_level2profile_availability_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_company_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level3profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_level3_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
